services:
  - type: web
    name: agentic-deep-researcher
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: pip install .
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_PORT
        value: "8501"

