# Render deployment configuration for Agentic Deep Researcher
services:
  - type: web
    name: agentic-deep-researcher
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_PORT
        value: "10000"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
      - key: STREAMLIT_SERVER_MAX_UPLOAD_SIZE
        value: "200"
      - key: STREAMLIT_SERVER_MAX_MESSAGE_SIZE
        value: "200"
      - key: STREAMLIT_LOGGER_LEVEL
        value: "info"
      - key: LITELLM_LOG
        value: "INFO"

